fix: updated templates

diff --git a/build/hooks/post-receive b/build/hooks/post-receive
--- a/build/hooks/post-receive
+++ b/build/hooks/post-receive
@@ -20,20 +20,24 @@ echo ""
 
 echo "Preparing deployment"
 
-[[ $REPO_NAME == "" ]] && exit 1
-
-if [ -d "$REPO_DEST" ]; then
-  echo "- Deployment for $REPO_NAME already exists"
-  echo "- Pulling changes ..."
-  pushd "$REPO_DEST" >/dev/null
-  unset GIT_DIR
-  git pull || exit 1
-  popd >/dev/null
-else
-  echo "- Creating deployment for $REPO_NAME"
-  git clone -q "$REPO_SRC" "$REPO_DEST" || exit 1
-  chown -R "git:git" "$REPO_SRC" "$REPO_DEST"
+if [ "$REPO_NAME" == "" ];
+then
+  echo "Couldn't determine repository name. Terminating."
+  exit 1
 fi
+
+# if [ -d "$REPO_DEST" ]; then
+#   echo "- Deployment for $REPO_NAME already exists"
+#   echo "- Pulling changes ..."
+#   pushd "$REPO_DEST" >/dev/null
+#   unset GIT_DIR
+#   git pull || exit 1
+#   popd >/dev/null
+# else
+#   echo "- Creating deployment for $REPO_NAME"
+#   git clone -q "$REPO_SRC" "$REPO_DEST" || exit 1
+#   chown -R "git:git" "$REPO_SRC" "$REPO_DEST"
+# fi
 
 echo ""
 # TODO: On docker error, abort git push.
@@ -43,6 +47,6 @@ echo ""
 # TODO: accept and deploy CI builds
 #swarmlet deploy "$REPO_DEST" || exit 1
 
-/usr/local/bin/backplane install "$REPO_NAME" "$REPO_DEST" || exit 1
+/usr/local/bin/backplane install "$REPO_NAME" --from "$REPO_SRC" || exit 1
 
 exit 0
